trigger: none
#  branches:
#    include:
#    - main
#    - dev

variables:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
  MONGODB_CONNECTION_PROTOCOL: mongodb
  MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: example
  PORT: 8080

stages:
- stage: BuildTest
  jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'
    container: node:16
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --env MONGO_INITDB_ROOT_USERNAME=root --env MONGO_INITDB_ROOT_PASSWORD=example
    steps:
    - checkout: self
